# -*- coding: utf-8 -*-
"""Aula-1 Visao natural e artificial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iixir0ILfqMyF9arhV2-TSf8sCv2UQxO
"""

import skimage as ski
import numpy as np
image =ski.io.imread("Lenna_(test_image) (1).png")
for i in range(len(image)):
  for j in range(len(image[i])):
    if image[i][j]>127:
      image[i][j]=255
    else:
      image[i][j]=0
ski.io.imshow(image)
ski.io.show()

import skimage as ski
import numpy as np
from skimage.color import rgb2gray
image =ski.io.imread("Cidade.png")
ski.io.imshow(image)
#ski.io.show()
#image_cinza=rgb2gray(image)
''''''
for i in range(len(image)):
  for j in range(len(image[i])):
    if j>len(image[0])/2:
      for k in range(len(image[i][j])):
        if image[i][j][k]<127:
          image[i][j][k]=0
        #elif image[i][j][k]<102:
        # image[i][j][k]=63
        #elif image[i][j][k]<153:
        #  image[i][j][k]=127
        #elif image[i][j][k]<204:
        #  image[i][j][k]=190
        else:
          image[i][j][k]=255

ski.io.imshow(image)
ski.io.show()
'''
for i in range(len(image_cinza)):
  for j in range(len(image_cinza[i])):
    if image[i][j]>127:
      image[i][j]=255
    else:
      image[i][j]=0
'''

import skimage as ski
import numpy as np
from skimage.color import rgb2gray
image =ski.io.imread("Lago.jpg")
image_cinza=[]

for i in range(len(image)):
  linha=[]
  for j in range(len(image[i])):
    linha.append((0.2125*image[i][j][0] + 0.7154*image[i][j][1] + 0.072*image[i][j][2])/255)
    if j>len(image[0])/2:
      if linha[-1]<0.1:
        linha[-1]=0
      elif linha[-1]<0.2:
        linha[-1]=0.11
      elif linha[-1]<0.3:
        linha[-1]=0.22
      elif linha[-1]<0.4:
        linha[-1]=0.33
      elif linha[-1]<0.5:
        linha[-1]=0.44
      elif linha[-1]<0.6:
        linha[-1]=0.55
      elif linha[-1]<0.7:
        linha[-1]=0.66
      elif linha[-1]<0.8:
        linha[-1]=0.77
      elif linha[-1]<0.9:
        linha[-1]=0.88
      else:
        linha[-1]=1
  image_cinza.append(linha)

imagem=np.array(image_cinza)
ski.io.imshow(imagem)
ski.io.show()